update CI for expected Pants versions

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -39,9 +39,9 @@ jobs:
             echo "ERROR: No wheel found in dist." 1>&2
             exit 1
           fi
-          for pants_version in 2.29 2.28 2.27 2.26 ; do
+          for pants_version in 2.30 2.29 2.28 ; do
             if [ ! -r dist/shoalsoft-pants-opentelemetry-plugin-pants${pants_version}-*.pex ]; then
-              echo "ERROR: No PEX file found for Pants version $pants_version." 1>&2
+              echo "ERROR: No PEX file found for Pants version ${pants_version}.x." 1>&2
               exit 1
             fi
           done
