distribute the plugin as a PEX and not as a wheel on (private) PyPI (#28)
Distribute the plugin in PEX form and not as a wheel. While testing the end user setup workflow for the plugin, Pants was taking 30-45 seconds to resolve the plugin from a private PyPI repository. This is not an acceptable end user experience.

Instead, the end user will now expand the plugin's pex file into a venv, and then update `[GLOBAL].pythonpath` to include that venv's `site-packages` directory. In testing of this solution, there is a negligible time cost for that in comparison to the abysmal plugin resolution time found when using wheels and a private PyPI repository.

The integration test is updated to make use of the PEX format.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -24,11 +24,12 @@ jobs:
         run: "pants lint check ::"
       - name: Run tests
         run: "pants test ::"
-      - name: Package for 2.25.x
-        run: "pants package src/python/shoalsoft/pants_telemetry_plugin:wheel-2.25"
-      - name: Package for 2.24.x
-        run: "pants package src/python/shoalsoft/pants_telemetry_plugin:wheel-2.24"
-      - name: Package for 2.23.x
-        run: "pants package src/python/shoalsoft/pants_telemetry_plugin:wheel-2.23"
-      - name: Package for 2.21.x
-        run: "pants package src/python/shoalsoft/pants_telemetry_plugin:wheel-2.21"
+      - name: Package plugin as PEX for various Pants versions.
+        run: |
+          pants package src/python/shoalsoft/pants_telemetry_plugin::
+          for pants_version in 2.25 2.24 2.23 2.21; do
+            if [ ! -r dist/shoalsoft-pants-telemetry-plugin-pants${pants_version}-*.pex ]; then
+              echo "ERROR: No PEX file found for plugin for Pants version $pants_version." 1>&2
+              exit 1
+            fi
+          done
