add testing Pants v2.31.x for testing (plus add back Pants v2.27.1) (#124)
Add Pants v2.31.0.dev1 for testing of Pants v2.31 series (and as the
repository's version). Also add back Pants v2.27.1 to continue testing
the Pants v2.27 series. (It was removed in
https://github.com/shoalsoft/shoalsoft-pants-opentelemetry-plugin/pull/122,
but I decided to include it again since 2.27.1 just was released.)

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -36,12 +36,12 @@ jobs:
         run: |
           pants package src/python/shoalsoft/pants_opentelemetry_plugin::
           if [ ! -r dist/shoalsoft_pants_opentelemetry_plugin-*-py3-none-any.whl ]; then
-            echo "ERROR: No wheel found in dist." 1>&2
+            echo "ERROR: No wheel found in `dist`." 1>&2
             exit 1
           fi
-          for pants_version in 2.30 2.29 2.28 ; do
+          for pants_version in 2.30 2.29 2.28 2.27 ; do
             if [ ! -r dist/shoalsoft-pants-opentelemetry-plugin-pants${pants_version}-*.pex ]; then
-              echo "ERROR: No PEX file found for Pants version ${pants_version}.x." 1>&2
+              echo "ERROR: No PEX file found for Pants version ${pants_version}.x found in `dist`." 1>&2
               exit 1
             fi
           done
