upload Python source archive to the draft release (#49)
Upload the source archive generated for the Python distribution to the
draft release.

diff --git a/.github/workflows/create-draft-release.yaml b/.github/workflows/create-draft-release.yaml
--- a/.github/workflows/create-draft-release.yaml
+++ b/.github/workflows/create-draft-release.yaml
@@ -1,8 +1,5 @@
 name: Create draft release
 on:
-  push:
-    tags:
-      - v*.*.*
   workflow_dispatch:
     inputs:
       ref:
@@ -48,11 +45,21 @@ jobs:
             echo "ERROR: No wheel file found at $wheel_file." 1>&2
             exit 1
           fi
+          source_archive_file="dist/shoalsoft_pants_opentelemetry_plugin-${{github.event.inputs.version}}.tar.gz"
+          if [ ! -r "$source_archive_file" ]; then
+           ls dist/* || true
+            echo "ERROR: No wheel file found at $wheel_file." 1>&2
+            exit 1
+          fi
           echo "wheel-local-path=$wheel_file" >> $GITHUB_OUTPUT
-      - name: Attest provenance of the wheel.
+          echo "source-archive-file=$source_archive_file" >> $GITHUB_OUTPUT
+          
+      - name: Attest provenance of the wheel and source archive.
         uses: actions/attest-build-provenance@v2
         with:
-          subject-path: ${{ steps.package.outputs.wheel-local-path }}
+          subject-path: |
+            ${{ steps.package.outputs.wheel-local-path }}
+            ${{ steps.package.outputs.source-archive-file }}
       - name: Create the draft release.
         uses: actions/github-script@v7
         env:
@@ -76,7 +83,9 @@ jobs:
             });
 
             return release.data;
-      - name: Upload the wheel to the draft release.
-        run: gh release upload ${{ github.event.inputs.ref }} ${{ steps.package.outputs.wheel-local-path }}
+      - name: Upload the wheel and source archive to the draft release.
+        run: |
+          gh release upload ${{ github.event.inputs.ref }} ${{ steps.package.outputs.wheel-local-path }}
+          gh release upload ${{ github.event.inputs.ref }} ${{ steps.package.outputs.source-archive-file }}
         env:
           GH_TOKEN: ${{ github.token }}
